[package]
name = "collector"
version = "0.1.0"
edition = "2021"

[dependencies]
serpapi-search-rust="0.1.1"
tokio.workspace=true
serde.workspace=true
serde_json.workspace=true
serde_derive.workspace=true
reqwest.workspace=true
select = "0.6.0"
futures.workspace=true
anyhow.workspace=true
